name: Build Bref PHP 8.3 Layer (GD + gRPC)

on:
  workflow_dispatch:

jobs:
  build-layer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # ✅ CHANGE if your region is different

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t php-layer .

      - name: Extract /opt and zip it
        run: |
          CONTAINER_ID=$(docker create php-layer)
          docker cp $CONTAINER_ID:/opt ./layer
          docker rm $CONTAINER_ID
          cd layer && zip -r ../layer.zip .

      - name: Publish to Lambda Layer
        run: |
          aws lambda publish-layer-version \
            --layer-name php-83-gd-grpc \
            --description "PHP 8.3 GD + gRPC layer" \
            --zip-file fileb://layer.zip \
            --compatible-runtimes provided.al2023 \
            --region us-east-1
